### ISSUE TITLE
Error response from daemon: removal of container wp_* is already in progress

### ISSUE THREAD

**Issue by xoxys** [woodpecker-ci/woodpecker#4784]
### Component

server

### Describe the bug

This issue appears quite often now. Example:

https://ci.woodpecker-ci.org/repos/8975/pipeline/1367/5

### Steps to reproduce

Not sure tbh.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-72823b7ffd"}
```

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by karatekaneen** [comment]
We also get this error quite often. Haven't been able to figure out under what conditions though

**Comment by pat-s** [comment]
I see it from my time to time and suspect it might be related to memory overconsumption for the affected builds. @xoxys @karatekaneen do you also have limits set in your instance?

**Comment by xoxys** [comment]
No

**Comment by karatekaneen** [comment]
No memory limits set. Although we are running Woodpecker on a relatively small VM, 4cpu and 8gb mem iirc

**Comment by outcast292** [comment]
Hello, 
I confirm, we get the error from time to time but can't seem to identify the source

**Comment by 6543** [comment]
should be fixed by https://github.com/woodpecker-ci/woodpecker/pull/6166

**Comment by xoxys** [comment]
> should be fixed by https://github.com/woodpecker-ci/woodpecker/pull/6166

Is it rolled out on ci.woodpecker-ci.org because there it still happens.

**Comment by 6543** [comment]
yes our ci is running from current next ...

I could not find such issue, you only have to consider today's pipelines as the rest did still where run with some older version containing bugs reacently fixed

the refactor was merged ~9 days ago and deployed ~7days or so

**Comment by xoxys** [comment]
https://ci.woodpecker-ci.org/repos/8975/pipeline/2841 rc137 should be "removal already in progress" even if the error text is not shown anymore... (whyever this was removed)

**Comment by 6543** [comment]
@xoxys DM via matrix to not spam this issue :)
